// File generated by FlutterFire CLI — manually corrected to use
// the com.apjtruelife.mobile Firebase app entry.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Usage:
/// ```dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web app config
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8KYDuoquvbRSSKjj4MD_1DbI5ZAjk1E0',
    appId: '1:873445934123:web:a5acdba96e29fcc74b966e',
    messagingSenderId: '873445934123',
    projectId: 'apj-true-life-909fa',
    authDomain: 'apj-true-life-909fa.firebaseapp.com',
    storageBucket: 'apj-true-life-909fa.firebasestorage.app',
    measurementId: 'G-7F20SGJ5T1',
  );

  // Android app config — uses com.apjtruelife.mobile package entry
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAghzvEs9Pj43X5p72U4Ab8nz2NPfA8M1E',
    appId: '1:873445934123:android:e78113414b1b20064b966e',
    messagingSenderId: '873445934123',
    projectId: 'apj-true-life-909fa',
    storageBucket: 'apj-true-life-909fa.firebasestorage.app',
  );

  // iOS app config
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2jZVqAqT6Gfod04HMOiHRgQx5S9rhS2E',
    appId: '1:873445934123:ios:9d6093e360700b5b4b966e',
    messagingSenderId: '873445934123',
    projectId: 'apj-true-life-909fa',
    storageBucket: 'apj-true-life-909fa.firebasestorage.app',
    iosBundleId: 'com.apjtruelife.mobile',
  );

  // macOS reuses the iOS config
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2jZVqAqT6Gfod04HMOiHRgQx5S9rhS2E',
    appId: '1:873445934123:ios:9d6093e360700b5b4b966e',
    messagingSenderId: '873445934123',
    projectId: 'apj-true-life-909fa',
    storageBucket: 'apj-true-life-909fa.firebasestorage.app',
    iosBundleId: 'com.apjtruelife.mobile',
  );

  // Windows web config
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8KYDuoquvbRSSKjj4MD_1DbI5ZAjk1E0',
    appId: '1:873445934123:web:c20d234fd44caf6c4b966e',
    messagingSenderId: '873445934123',
    projectId: 'apj-true-life-909fa',
    authDomain: 'apj-true-life-909fa.firebaseapp.com',
    storageBucket: 'apj-true-life-909fa.firebasestorage.app',
    measurementId: 'G-JC4MB8VW1L',
  );
}
