# APJ TRUE LIFE — treatment-service v2.0

spring:
  application:
    name: treatment-service
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DATABASE_URL_RUNTIME:jdbc:postgresql://localhost:5432/apjtruelife?user=apjdev&password=apjdev&prepareThreshold=0}
    driver-class-name: org.postgresql.Driver

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info
