server:
  port: 8086

spring:
  application:
    name: chat-service
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    schemas: chat
    locations: classpath:db/migration
    baseline-on-migrate: true

app:
  jwt:
    secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info
